version: '3.7'

services:
  delibasket-backend:
    container_name: delibasket-backend
    command: uvicorn application.main:app --reload --host 0.0.0.0
    volumes:
      - ../backend:/srv/www/app/
      - media_value:/srv/www/app/application/media

  frontend:
    container_name: frontend
    build:
     context: ../frontend
     dockerfile: Dockerfile
