version: '3.7'

services:
  delibasket-db:
    container_name: ${POSTGRES_SERVER}
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/delibasket/
    command: -p ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./.env

  delibasket-redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/var/lib/redis/delibasket/
    command: >
        --requirepass ${REDIS_PASSWORD}

  delibasket-backend:
    container_name: delibasket-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: gunicorn application.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    restart: always
    volumes:
      - media_value:/srv/www/app/application/media
    env_file:
      - ./.env
    ports:
      - 9988:8000
    depends_on:
      - delibasket-db
      - delibasket-redis

  frontend:
    container_name: frontend
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - delibasket-backend

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - media_value:/var/html/media/
    depends_on:
      - delibasket-backend
      - frontend

volumes:
  media_value:
  postgres_data:
  redis_data: