version: '3.7'

services:
  delibasket-db:
    container_name: ${POSTGRES_SERVER}
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/delibasket/
    command: -p ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./.env
    networks:
      - delibasket

  delibasket-redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/var/lib/redis/delibasket/
    command: >
        --requirepass ${REDIS_PASSWORD}
    networks:
      - delibasket

  delibasket-backend:
    container_name: delibasket-backend
    <<: &delibasket-backend
      image: ${DOCKERHUB_USERNAME}/backend:latest
      restart: always
      networks:
        - delibasket
      env_file:
        - ./.env
      depends_on:
        - delibasket-db
        - delibasket-redis
    command: gunicorn application.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    volumes:
      - media_value:/srv/www/app/application/media
    ports:
      - 9988:8000

  frontend:
    container_name: frontend
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - delibasket-backend
    networks:
      - delibasket

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
    depends_on:
      - delibasket-backend
      - frontend
    networks:
      - delibasket

volumes:
  media_value:
  postgres_data:
  redis_data:

networks:
  delibasket: