version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    #command: uvicorn main:app --reload --host 0.0.0.0
    restart: always
    volumes:
      - ../backend/:/backend
      - media_value:/backend/media
    env_file:
      - ./.env
    ports:
      - 0:8000
    depends_on:
      - db

  frontend:
    image: kekkisama/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  media_value:
  postgres_data: