version: '3.7'

services:
  db:
    container_name: ${POSTGRES_SERVER}
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../backend/:/backend
      - media_value:/backend/media
    env_file:
      - ./.env
    ports:
      - 9999:8000
    depends_on:
      - db

  frontend:
    image: kekkisama/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  media_value:
  postgres_data: