"""Initial

Revision ID: 235b750b8f5f
Revises: eeb501ef3138
Create Date: 2023-08-29 07:33:34.589418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '235b750b8f5f'
down_revision = 'eeb501ef3138'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredient_name', table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_table('amount_ingredient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amount_ingredient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('amount > 0', name='amount_ingredient_amount_check'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='amount_ingredient_ingredient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='amount_ingredient_recipe_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='amount_ingredient_pkey'),
    sa.UniqueConstraint('ingredient_id', 'recipe_id', name='amount_ingredient_ingredient_id_recipe_id_key')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('measurement_unit', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ingredient_pkey'),
    sa.UniqueConstraint('name', 'measurement_unit', name='ingredient_name_measurement_unit_key')
    )
    op.create_index('ix_ingredient_name', 'ingredient', ['name'], unique=False)
    # ### end Alembic commands ###
