"""Initial

Revision ID: 1bf071ba95d1
Revises: 
Create Date: 2022-12-12 09:17:58.253230

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1bf071ba95d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
